projectID: "datcom-mixer-encode"
instance: "prophet-test"
cluster: "prophet-test-c1"
dataflowTemplate: "gs://datcom-dataflow-templates/templates/flex/csv_to_bt.json"
tempLocation: "gs://datcom-store-dev-resources/dataflow/tmp"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-dev"
bucket: "datcom-mixer-encode-resources"
dataDirectory: "demo/data/"
