projectID: "datcom-stanford-staging"
instance: "dc-graph"
cluster: "dc-graph-c1"
nodesHigh: "3"
nodesLow: "1"
dataflowTemplate: "gs://datcom-templates/templates/flex/csv_to_bt_0.0.3.json"
tempLocation: "gs://datcom-stanford-staging-resources/dataflow/tmp"
bucket: "datcom-stanford-staging-resources"
controllerTriggerTopic: "projects/datcom-204919/topics/private-import-notification-prod"
gcfSA: "website-robot@datcom-stanford-staging.iam.gserviceaccount.com"
